spring.application.name=Spring
spring.datasource.url=jdbc:mysql://localhost:3306/gestao_fila_atendimento
spring.datasource.username=root
spring.datasource.password=Jp040771@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
