name: CI

on:
  push:
    branches: [ "main", "v2-melhorias" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodar testes com Maven
        run: ./mvnw test
          - name: Dar permissão de execução ao mvnw
              working-directory: ./Spring
              run: chmod +x mvnw
                - name: Rodar testes com Maven
                  working-directory: ./Spring
                  run: ./mvnw test

